version: "3.9"

services:
  db:
    image: postgres:15
    container_name: kartquake-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kartquake
      POSTGRES_USER: kartquake
      POSTGRES_PASSWORD: kartquake
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: kartquake-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
